config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get 'user/profile'
  devise_for :users, controllers:{
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  get 'u/:id', to: 'user#profile', as: 'user'

  # /posts/1/comments/4
  resources :posts do
        resources :comments
  end
  get 'pages/about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body

  after_create_commit :notify_recipient
  before_destroy :cleanup_notification
  has_noticed_notifications model_name: 'Notification'

  private
  def notify_recipient
    CommentNotification.with(comment: self, post: post).deliver_later(post.user)
  end

  def cleanup_notification
    notifications_as_comment.destroy_all
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum:5, maximum:50}
  validates :body, presence: true, length: {minimum:10, maximum: 200}
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["body", "title"]
    end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["email", "name"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_notification, if: :current_user
  before_action :set_query

  def set_query
    @query = Post.ransack(params[:q])
  end


  private


  def set_notification
    notification = Notification.where(recipient: current_user).newest_first.limit(9)
    @unread = notification.unread
    @read = notification.read
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  def create

    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "comment successfully created"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Something went wrong"
      redirect_to post_path(@post)
    end
  end
  def update
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
      format.html { redirect_to post_url(@post), notice: 'Comment has been updated sucessfully' }
      else
      format.html { redirect_to post_url(@post), notice: 'Comment was not updated' }
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      flash[:notice] = "comment successfully destroyed"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Something went wrong"
      redirect_to post_path(@post)
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(view: (@post.view || 0 ) + 1)
    @comments = @post.comments.order(created_at: :desc)
    mark_notification_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def mark_notification_as_read
      if current_user
        mark_notification_as_read = @post.notifications_as_post.where(recipient: current_user)
        mark_notification_as_read.update_all(read_at: Time.zone.now)
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="comment-<%= comment.id %> container"
    style="border: 1px solid black; padding: 1em; margin: 1em;">
  <%= comment.user.email %><br />
  
  <% if (comment.updated_at - comment.created_at) > 1 %>
    <span> Edited <%= time_ago_in_words(comment.updated_at)%> ago </span>
  <% else %>
  <span>Posted <%= time_ago_in_words(comment.created_at) %></span>
  <% end %>  
  <% if current_user == comment.user %>
    <div class="btn-group float-end">
      <%= link_to "Edit", nil, remote: true, class:"btn btn-warning",
      data: { 
        controller: "comments",
        action: "comments#toggleForm",
        comments_form_param: "edit-form-#{comment.id}",
        comments_body_param: "comment-body-#{comment.id}",
        comments_edit_param: "comment-edit-#{comment.id}",  
      },
      id: "edit-button-#{comment.id}"%>

      <%= button_to "Delete", [post, comment], class:"btn btn-danger", method: :delete %>
    </div>
    <div id="edit-form-<%= comment.id%>" class="d-none">
      <%= render 'comments/form', 
      post: @post, 
      comment: comment,
      submit_label: "Update" %>
    </div>
  <% end %>
  <hr />
  <div id="comment-body-<%= comment.id%>">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |f| %>
  <div class="form-control">
    <%= f.rich_text_area :body %>
    <%= f.submit submit_label, class: "btn btn-primary mt-1" %>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Rails Blog", root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", posts_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", pages_about_path, class:'nav-link'%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= render 'search/form' %>
        <%= render 'layouts/notifications' %>
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<li class="dropdown-item">
    <%= link_to notification.to_notification.message, notification.to_notification.url %>
</li>

app/views/layouts/_notifications.html.erb
<%if current_user%>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="badge rounded-pill bg-danger">
                <%= @unread.count >= 9 ? "9+" : @unread.count%> <i class="bi bi-suit-heart-fill"></i>
            </span>
        </a>
        
        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
            <% @unread.each do |notification|%>
                <%= render 'layouts/notification', notification: notification %>
            <% end %>           
        
        
            <% if @read.count > 0 && @unread.count > 0 %>
                <li>
                    <hr class="dropdown-divider">   
                </li>
            <% elsif @read.count + @unread.count == 0 %>
                <li class="dropdown-item">
                    No notification yet.
                </li>
            <% end %>

            <% @read.each do |notification|%>
                <%= render 'layouts/notification', notification: notification %>
            <% end %>    
        </ul>
    </li>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/show.html.erb
<div class="container">  
  <%= render @post %>
  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>
    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
</div>
<div class="container">
  <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: "Reply" %>
  
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>  
  <% end %>
  
</div>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class: 'd-flex') do |f|%>
    <%= f.search_field :title_or_body_or_user_email_or_user_name_i_cont_any,
    placeholder: "Search...",
    class: "form-control me-2"%>
    <%= f.submit "Search!", class:"btn btn-outline-success"%>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center"><%= pluralize(@posts.count, "Result")%></h1>
<%= render 'search/form' %>

<div class="container">
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th><%= sort_link(@query, :title, "Title", default_oder: :asc)%></th>
            <th><%= sort_link(@query, :body, "Blog content")%></th>
            <th><%= sort_link(@query, :user_name, "Users")%></th>
            <th></th>
        </tr>
        </thead>

        <tbody>            
            <% @posts.each do |post| %>
            <tr>
                <td><%= link_to post.title, post %></td>
                <td><%= post.body.truncate_words(10) %></td>                
                <td><%= link_to post.user.name, post.user %></td>                
            </tr>
            <% end %>           
        </tbody>
    </table>
</div>